# Generated by Django 3.0.3 on 2020-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('class_name', models.CharField(choices=[('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=30)),
                ('school_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(upload_to='junior_photos')),
                ('payment_status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
