# Generated by Django 3.0.3 on 2020-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20200815_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorround',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
